# -*- coding: utf-8 -*-
"""UIDAI_Aadhaar_Risk_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15w_76BZOU3PYOrAaxyuEQO8SLrmrpa-y
"""

!pip install pandas numpy scikit-learn

import pandas as pd
import numpy as np

from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import MinMaxScaler

df_part1 = pd.read_csv("api_data_aadhar_enrolment_0_500000.csv")
df_part2 = pd.read_csv("api_data_aadhar_enrolment_500000_1000000.csv")
df_part3 = pd.read_csv("api_data_aadhar_enrolment_1000000_1006029.csv")

df = pd.concat([df_part1, df_part2, df_part3], ignore_index=True)

df.head()

df = df.rename(columns={
    'Date' : 'date',
    'State Name': 'state',
    'District Name': 'district',
    'Pincode': 'pincode',
    'Age_0_5': 'age_0_5',
    'Age_5_17': 'age_5_17',
    'Age_18_': 'age_18_greater'
})

df['date'] = pd.to_datetime(df['date'], format='%d-%m-%Y', errors='coerce')
df['month'] = df['date'].dt.month

df['total_enrolments'] = df['age_0_5'] + df['age_5_17'] + df['age_18_greater']
df['child_enrolments'] = df['age_0_5'] + df['age_5_17']
df['adult_enrolments'] = df['age_18_greater']

df = df.sort_values(['district', 'month'])

df['rolling_mean_3'] = df.groupby('district')['total_enrolments'] \
    .transform(lambda x: x.rolling(3, min_periods=1).mean())

df['rolling_std_3'] = df.groupby('district')['total_enrolments'] \
    .transform(lambda x: x.rolling(3, min_periods=1).std())

df['spike_score'] = (df['total_enrolments'] - df['rolling_mean_3']) / \
    (df['rolling_std_3'] + 1)

df['child_adult_ratio'] = df['child_enrolments'] / \
    (df['adult_enrolments'] + 1)

df['mom_growth'] = df.groupby('district')['total_enrolments'] \
    .pct_change().fillna(0)

features = df[['total_enrolments',
               'spike_score',
               'child_adult_ratio',
               'mom_growth']].fillna(0)

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(features)

model = IsolationForest(
    n_estimators=200,
    contamination=0.08,
    random_state=42
)

df['anomaly_flag'] = model.fit_predict(X_scaled)
df['anomaly_score'] = model.decision_function(X_scaled)

df['norm_anomaly'] = MinMaxScaler().fit_transform(
    df[['anomaly_score']]
)

df['norm_spike'] = MinMaxScaler().fit_transform(
    df[['spike_score']]
)

df['norm_child_skew'] = MinMaxScaler().fit_transform(
    df[['child_adult_ratio']]
)

df['risk_score'] = (
    0.4 * (1 - df['norm_anomaly']) +
    0.3 * df['norm_spike'] +
    0.3 * df['norm_child_skew']
) * 100

def risk_label(score):
    if score >= 70:
        return "HIGH (Audit Recommended)"
    elif score >= 40:
        return "MEDIUM (Monitor)"
    else:
        return "LOW (Normal)"

df['risk_level'] = df['risk_score'].apply(risk_label)

df['explanation'] = np.where(
    df['risk_score'] >= 70,
    "Abnormal enrolment spike & demographic skew detected",
    "Normal enrolment behavior"
)

df[['state', 'district', 'month',
    'risk_score', 'risk_level', 'explanation']].head(300)

df.to_csv("aadhaar_risk_output.csv", index=False)
